######################################################################
# Automatically generated by qmake (3.0) Tue Jan 27 16:44:13 2015
######################################################################

TEMPLATE = app
TARGET = 03_qmake
INCLUDEPATH += .

# Input
SOURCES += src/main.cpp
